### ISSUE TITLE
Add ability to configure the `InMemoryDirectoryServer`

### ISSUE THREAD

**Issue by boris-petrov** [zapodot/embedded-ldap-junit#101]
I would like to use `setMaxSizeLimit` of the `InMemoryDirectoryServerConfig` because I want to test my pagination implementation. Right now I have to call `EmbeddedLdapRuleImpl.createForConfiguration` and do manually what [createInMemoryServerConfiguration](https://github.com/zapodot/embedded-ldap-junit/blob/v.0.8.1/src/main/java/org/zapodot/junit/ldap/EmbeddedLdapRuleBuilder.java#L186) does. It would be nice to have that feature.

**Comment by zapodot** [comment]
Just release v. 0.8.3 that includes the builder method `withMaxSizeLimit(int)` that allows providing this setting. Thank you for suggesting this
