### ISSUE TITLE
Can not get a LdapConnection before the embedded LDAP server has been started

### ISSUE THREAD

**Issue by mohamed-amine-turki** [zapodot/embedded-ldap-junit#65]
I keep getting this error message `Can not get a LdapConnection before the embedded LDAP server has been started`
I'm using scala and this is my code: 
`val embeddedLdapRule: EmbeddedLdapRule = EmbeddedLdapRuleBuilder.newInstance().usingDomainDsn(DOMAIN_DSN)
        .importingLdifs("users-import.ldif").build()
      val ldapConnection = embeddedLdapRule.ldapConnection()
      val searchResult = ldapConnection.search(DOMAIN_DSN, SearchScope.SUB, "(objectClass=person)")
      searchResult.getEntryCount shouldBe 3`
the error is thrown at this line `val ldapConnection = embeddedLdapRule.ldapConnection()`

**Comment by zapodot** [comment]
It is supposed to be used in the context of a Junit test as the actual setup of the connection is created right before the test is started. I can not see whether that is what you are trying to do here. Please reopen if you have more details
